# Generated by Django 5.0.3 on 2024-03-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=128)),
                ('eventStatus', models.CharField(max_length=12)),
                ('eventDateHour', models.DateTimeField(blank=True)),
                ('eventSeatAvailable', models.IntegerField(blank=True)),
                ('eventPlace', models.CharField(max_length=128)),
                ('eventPic', models.ImageField(blank=True, null=True, upload_to='event_pic')),
            ],
        ),
    ]
