# Generated by Django 5.0.3 on 2024-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventSlug',
            field=models.SlugField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
