# Generated by Django 5.0.3 on 2024-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mgmt', '0002_event_eventslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDescription',
            field=models.TextField(blank=True),
        ),
    ]
