# Generated by Django 5.0.3 on 2024-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mgmt', '0007_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
