# Generated by Django 5.0.3 on 2024-04-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mgmt', '0008_event_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventSlug',
            field=models.SlugField(blank=True, max_length=128),
        ),
    ]
