# Generated by Django 5.0.3 on 2024-04-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mgmt', '0009_alter_event_eventslug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventStatus',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventPlace',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
