# Generated by Django 5.0.3 on 2024-04-12 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mgmt', '0010_remove_event_eventstatus_alter_event_eventplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDateHour',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 12, 13, 45, 50, 465932, tzinfo=datetime.timezone.utc)),
        ),
    ]
