# Generated by Django 5.0.3 on 2024-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_mgmt', '0011_alter_event_eventdatehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventDateHour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
