# Generated by Django 5.0.3 on 2024-04-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eticket',
            old_name='event',
            new_name='event_ticket',
        ),
        migrations.RenameField(
            model_name='eticket',
            old_name='user',
            new_name='user_ticket',
        ),
    ]
