# Generated by Django 5.0.3 on 2024-04-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0002_rename_event_eticket_event_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eticket',
            old_name='event_ticket',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eticket',
            old_name='user_ticket',
            new_name='user',
        ),
    ]
