# Generated by Django 5.0.3 on 2024-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eticketing', '0003_rename_event_ticket_eticket_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eticket',
            name='offer',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
